# Site settings
author: Evan Smith
title: Coding With Evan
header-img: img/home-bg.png
email: professionalemail@zoho.com
copyright_name: Evan Smith
description: > # this means to ignore newlines until "baseurl:"
  learning to code, boot-camp-style
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  EvanTheSmith

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
